from typing import Protocol, runtime_checkable
from uuid import UUID

from app.domain.project import Project


@runtime_checkable
class ProjectRepository(Protocol):
    def ping(self) -> bool: ...
    def list_projects(self, sort: str = "name_asc") -> list[Project]: ...
    def get_project(self, project_id: UUID) -> Project | None: ...
    def create_project(self, name: str) -> Project: ...
    def save_project(self, project: Project) -> Project: ...
    def delete_project(self, project_id: UUID) -> None: ...
